### ISSUE TITLE
One can add a product with a negative price

### ISSUE THREAD

**Issue by C0rby** [fablabnbg/Matomat_md#11]
To reproduce:
1. Put someting in the clipboard e.g. "-42"
2. Type a name
3. Press tab to switch in the price input field
4. Paste the clipboard in to the field
5...
6. Profit!

Also works with characters like "foo"

**Comment by pathim** [comment]
Primarily a backend issue. The backend should check the validity of the given price.
For the frontend the ability to input prices that will be rejected (if the check were implemented on the backend) is only a minor usability issue.

If someone wants to write a patch feel free to send a pull request. I think it is not important enough and will close the issue.
